name: Run tests and create tag (if on main)

on:
  push:
  pull_request:

jobs:
  build-n-publish:
    name: Build and publish coh_piggs_extractor to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: ls -al
      - run: pip install nose
      - run: nosetests
